title: VX Reloaded
author:
  name: Aleksey
  email: anon@4chan.org
description: > # this means to ignore newlines until "show_excerpts:"
  A place for those feeling the nostalga of 1990s VX scene, and for those who want to write virii for fun, and not profit.

url: "https://vxreloaded.github.io"

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  
collections:
  pages:
    output: true

  # generate social links in footer
  social_links:
    # twitter: 
    github:  jekyll
    # devto: 
    # dribbble: 
    # facebook: 
    # flickr: 
    # instagram: 
    # linkedin: 
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # keybase: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

    # GitLab instances
    # gitlab:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:

# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-sitemap
